name: create_container_infra
on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/create_container_infra.yml'
      - 'container_infra/modules/**'
      - 'container_infra/**.tf'
jobs:
  terraform_plan:
    defaults:
      run:
        working-directory: ./orchestration
    runs-on: ubuntu-latest
    env:
      USERNAME: ${{ secrets.USERNAME }}
      PROJECT_PATH: ${{ secrets.PROJECT_PATH }}
      STAGE_FILE: "docker-compose.network-infra.yml"
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_SESSION_TOKEN:  ${{ secrets.AWS_SESSION_TOKEN }} 
    steps:
    - uses: actions/checkout@v2
    - name: Terraform_Plan
      run: make run_plan

  terraform_apply:
    defaults:
      run:
        working-directory: ./orchestration
    environment:
      name: approval
    needs: terraform_plan
    runs-on: ubuntu-latest
    env:
      USERNAME: ${{ secrets.USERNAME }}
      PROJECT_PATH: ${{ secrets.PROJECT_PATH }}
      STAGE_FILE: "docker-compose.container-infra.yml"
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_SESSION_TOKEN:  ${{ secrets.AWS_SESSION_TOKEN }} 
    steps:
    - uses: actions/checkout@v2
    - name: Terraform_Plan
      run: make run_plan
    - name: Terraform_Apply
      run: make run_apply

  docker_image_build:
    defaults:
      run:
        working-directory: ./weather_app
    needs: terraform_apply
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }} 
      ACCOUNT_ID: ${{ secrets.ACCOUNT_ID }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      REPO_NAME: ${{ secrets.REPO_NAME }}
    steps:
    - uses: actions/checkout@v2
    - name: Log into ECR
      run: make login_ecr
    - name: Create Docker image
      run: make build_docker
    - name: Push Docker image
      run: make push_image
