name: destroy_container_infra
on:
  workflow_dispatch:
  push:
    branches:
      - destroy
    paths:
      - 'container_infra/docker-compose.yml'
      - 'container_infra/Makefile'
      - '.github/workflows/destroy_container_infra.yml'
      - 'container_infra/*dockerfile'
      - 'container_infra/modules/**'
      - 'container_infra/**.tf'

jobs:
  terraform_destroy_plan:
    defaults:
      run:
        working-directory: ./container_infra
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_SESSION_TOKEN:  ${{ secrets.AWS_SESSION_TOKEN }} 
    steps:
    - uses: actions/checkout@v2
    - name: Terraform_Destroy_Plan
      run: make run_destroy_plan       

  terraform_destroy_apply:
    defaults:
      run:
        working-directory: ./container_infra
    environment:
      name: approval
    needs: terraform_destroy_plan
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_SESSION_TOKEN:  ${{ secrets.AWS_SESSION_TOKEN }} 
    steps:
    - uses: actions/checkout@v2
    - name: Terraform_Destroy_Apply
      run: make run_destroy_apply 
